uploads = []

[[generated]]
id = "NZQcvY_SD2QMXXAY07dQ-"
uri = "file://artifacts/authentic-steps/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "ezUhRuVjcnAfkdbm_VbJt"
uri = "file://.local/outputs/Authentic-Steps-Founder-Pitch.pptx"
type = "slides"
title = "Authentic Steps Founder Pitch (PPTX)"

[[outputs]]
id = "CVaWXdXIsSahARdK1jxeK"
uri = "file://.local/outputs/Authentic-Steps-Founder-Pitch.pdf"
type = "pdf"
title = "Authentic Steps Founder Pitch (PDF)"

[[outputs]]
id = "OlnVYb-NNLfXLrch3reDr"
uri = "file://.local/outputs/Authentic-Steps-Founder-Pitch-Deck.pdf"
type = "pdf"
title = "Authentic Steps — Founder Pitch Deck (PDF)"

[[outputs]]
id = "IwA32nA9Ub-8NCSCXMVlF"
uri = "file://.local/outputs/Authentic-Steps---Founder-Pitch-Deck.pptx"
type = "slides"
title = "Authentic Steps — Founder Pitch Deck (PPTX)"

[[outputs]]
id = "w19r4w_g0NwW7DX4_IE5k"
uri = "file://.local/outputs/Authentic-Steps-Founder-Pitch-Deck.pptx"
type = "slides"
title = "Authentic Steps — Founder Pitch Deck (PPTX)"

[[outputs]]
id = "_v2uncJxP7n_oS3ix8mHn"
uri = "file://.local/outputs/Authentic-Steps-Founder-Pitch-Deck-compressed.pptx"
type = "slides"
title = "Authentic Steps — Founder Pitch Deck (PPTX)"

[[outputs]]
id = "XAZcNLlf9WHT5ktc4be6c"
uri = "file://.local/outputs/Authentic-Steps-Youth.pptx"
type = "slides"
title = "Authentic Steps Youth.pptx"
